artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1t0fXtg3ibJ59KWYeUT_paKpguzJqLp-v/view?usp=sharing
  local_data_file: artifacts/data_ingestion/kidneydataset.zip
  unzip_dir: artifacts/data_ingestion